### ISSUE TITLE
tag a release

### ISSUE THREAD

**Issue by dvzrv** [mgedmin/coverage-highlight.vim#13]
Hi! I would like to move this plugin as a package to the official repositories on Arch Linux.
Could you tag releases of this repository, matching the version of the plugin?

I can only package releases.

Thanks!

**Comment by mgedmin** [comment]
Tagged 3.0, will that suffice?

**Comment by dvzrv** [comment]
Now in the repos: https://www.archlinux.org/packages/community/any/vim-coverage-highlight/
