### ISSUE TITLE
LICENSE file missing

### ISSUE THREAD

**Issue by dvzrv** [mgedmin/coverage-highlight.vim#14]
Hi! As a follow up to #13 (sorry for the long delay :-/) I realized, that a LICENSE file is missing in this repository.
However, for me it is required to add this to the package to be able to distribute it, as at the bottom of the README.md you specify this code to be covered by the MIT license.
The MIT license text has unique fields, that identify the copyright holders by name (this is unlike e.g. the GPL), which is why we have to include this license file in a package.

The standard MIT license text can be found [here](https://spdx.org/licenses/MIT.html#licenseText).
You would need to replace the text in red with your name and the current year and tag a new release.

**Comment by mgedmin** [comment]
Thank you for bringing this to my attention!

**Comment by mgedmin** [comment]
I suppose I should tag a new release?

**Comment by mgedmin** [comment]
Tagged 3.0.1.
