### ISSUE TITLE
Incompatibility with coverage > 5.0

### ISSUE THREAD

**Issue by dvzrv** [mgedmin/coverage-highlight.vim#15]
When using coverage > 5.0 [the .coverage file is now an SQLite database and not a JSON file anymore](https://coverage.readthedocs.io/en/coverage-5.0.4/whatsnew5x.html?highlight=sqlite).

I think similar functionality to before can be achieved by analyzing not the .coverage file directly but one of the several output formats (e.g. `coverage json` or `coverage xml`).

**Comment by mgedmin** [comment]
This plugin is not analyzing .coverage files directly.  It runs `coverage report` as a subprocess and parses its output.  It works fine with coverage > 5.0 (with all versions of coverage actually), as long as the version of coverage you get in your $PATH matches the version of coverage that generated the .coverage file.

You can set g:coverage_script to the path of your `coverage` command if the one in $PATH is wrong for a particular project.

**Comment by dvzrv** [comment]
Oh, I didn't realize!
I'm currently in the weird spot of having coverage < 5.0.0 installed system-wide, but coverage > 5.0.0 in a venv in tox. So every time tox generates the .coverage I can of course not use the system coverage to try and use it! -_-

Thanks for the clarification!
In my case `:let g:coverage_script=".tox/coverage/bin/coverage"` fixed it.
