### ISSUE TITLE
Toggling the coverage highlighting

### ISSUE THREAD

**Issue by neuneck** [mgedmin/coverage-highlight.vim#16]
I love toggles for thing like code highlighting!
Coverage-highlight provides both `:HighlightCoverage` and `:HighlightCoverageOff`.

Would it be possible to have a `:HighlightCoverageToggle` that turns the highlighting on, if it's currently off and vice versa?

**Comment by neuneck** [comment]
Yeah. Just found `ToggleCoverage` in the code. Sorry, I should have looked there, first!
Thanks for the useful plugin!

**Comment by mgedmin** [comment]
Would you like to help me write a help page for this plugin?

I also have totally forgotten that :ToggleCoverage existed!  :)
