### ISSUE TITLE
Better feedback when coverage script can't be found

### ISSUE THREAD

**Issue by jsatt** [mgedmin/coverage-highlight.vim#18]
I just spent a good while trying to troubleshoot the plugin not working because the feedback was "Neither .coverage nor ... found." when the .coverage file clearly existed. After some digging I found that it was really because the coverage script wasn't in the PATH that the plugin was looking up, using the environment variable, and I just needed to set the `g:coverage_script` explicitly.

**Comment by mgedmin** [comment]
Oops you're right, the error message is wrong in this situation.

**Comment by jsatt** [comment]
Awesome, thanks.
