### ISSUE TITLE
Problems with new "TOTAL" line in coverage >= 5.4

### ISSUE THREAD

**Issue by dvzrv** [mgedmin/coverage-highlight.vim#20]
Hi! The plugin unfortunately breaks on coveragepy >= 5.4, as they have introduced an additional `TOTAL` line also for single file reports: https://github.com/nedbat/coveragepy/issues/1086

When trying to display coverage this looks roughly as the following:

```
Running coverage report -m <directory>/<file>.py
Got confused by 'TOTAL                         1228    113    510     20    89.36%'
Expected it to start with '<directory>/<file> '
Full output:
Name                         Stmts   Miss Branch BrPart     Cover   Missing
---------------------------------------------------------------------------
<directory>/<file>.py    1228    113    510     20    89.36%   43->47, 47-50, 78->82, 82-85, 113->117, 117-120, 212, 352-418, 616->617, 616->620, 617-623, 656->657, 656->661, 657-661, 691->692, 691->696, 692-696, 989->990, 990, 1029->1033, 1033, 1067->1071, 1071, 1105->1109, 1109, 3455->3456, 3455->3459, 3456-346
2, 3516->3521, 3521, 3551-3555, 3584->3585, 3585, 3615->3616, 3616, 4343-4366, 4396-4419, 4590->4591, 4590->4594, 4591-4603, 4991-5010
---------------------------------------------------------------------------
TOTAL                         1228    113    510     20    89.36%
```

**Comment by mgedmin** [comment]
I've merged a pull request fixing this very recently (#19).  Can you double-check if you're using the latest plugin code?

**Comment by dvzrv** [comment]
@mgedmin Thanks for the fast response!
I'm currently packaging 3.0.1 on Arch Linux but can certainly apply the patch from that pull request (sorry, I didn't look before writing), but it does not apply cleanly.

It would be awesome if you can find the time to tag another release, which includes this fix.

**Comment by mgedmin** [comment]
Oops, I've forgotten to add git tags after bumping the version!

Tagged 3.3 now (and also the forgotten earlier 3.2 and 3.1).

**Comment by dvzrv** [comment]
Many thanks! Updating now! :)
