### ISSUE TITLE
Silent commands

### ISSUE THREAD

**Issue by azmeuk** [mgedmin/coverage-highlight.vim#25]
Hi. Thank you for this amazing extension. I enabled it on each buffer opening or saving with `autocmd! BufWritePost,BufEnter *.py HighlightCoverageForAll`, but now each time I save a file I must press **Enter** to confirm the file saving.

![Capture d’écran du 2021-07-16 13-34-13](https://user-images.githubusercontent.com/60163/125941533-48cfb0d0-a4bf-407c-93b9-3151f15acea3.png)

I suppose it is due to the extension writing things in stdout.

I suggest adding an option to silent the extension output.

**Comment by mgedmin** [comment]
You should be able to suppress these messages by using `:silent HighlightCoverageForAll`.

**Comment by azmeuk** [comment]
Indeed `autocmd! BufWritePost,BufEnter *.py silent HighlightCoverageForAll` does the trick. Thank you!
