### ISSUE TITLE
Getting "Press enter to continue" when enabling coverage

### ISSUE THREAD

**Issue by jwodder** [mgedmin/coverage-highlight.vim#28]
When I run `:HighlightCoverage` on a typical Python source file of mine, this is what I see at the bottom of my screen:

```
Running coverage report -m src/headerparser/parscls.py
src/headerparser/parscls.py     244     12     8...
Press ENTER or type command to continue
```

(I am using Vim 8.2.3550, `verbose` is 0, and `v:echospace` is 51.)

Judging from [this comment](https://github.com/mgedmin/coverage-highlight.vim/blob/e49a7cb3a875f4eddd97565419d5deb7b33c272f/pythonx/coverage_highlight.py#L301), it seems that the intended behavior of this plugin is that the user generally should not need to press enter after enabling coverage, yet, due to [this `print()` statement](https://github.com/mgedmin/coverage-highlight.vim/blob/e49a7cb3a875f4eddd97565419d5deb7b33c272f/pythonx/coverage_highlight.py#L423), an extra line is printed when coverage is loaded, leading to the need to press enter.  Is this net behavior intentional or not?

**Comment by mgedmin** [comment]
What is your `&cmdheight`?  Vim's default is 1, my .vimrc sets it to 2.

It's generally a goal for me to avoid hit-enter prompts on `:HighlightCoverage`.  Currently that assumes &cmdheight is at least 2, as it prints two lines of information: the command that it runs, and its output.  I can check the &cmdheight value and print only one of the two lines.

If you had to choose which one to see, what would you pick -- the command or the output?

**Comment by jwodder** [comment]
> What is your `&cmdheight`?

It's 1, and I think I'd rather keep it that way.

> If you had to choose which one to see, what would you pick -- the command or the output?

The output.  I don't care what command is being run behind the scenes; the actual file coverage value is more relevant.

**Comment by mgedmin** [comment]
Could you test if https://github.com/mgedmin/coverage-highlight.vim/pull/30 fixes the problem for you?

**Comment by jwodder** [comment]
@mgedmin As-is, it changes nothing.  I have to wrap `vim.eval('&cmdheight')` in `int(...)` to get it to work.

**Comment by mgedmin** [comment]
Welp, then the same fix also needs to be done on `vim.eval('&wrapscan')`!

**Comment by mgedmin** [comment]
(Pushed fix to branch)

**Comment by jwodder** [comment]
@mgedmin So... do you want me to update the `vim.eval('&wrapscan')` call?  Either way, what needs to be done to get #30 merged?

**Comment by mgedmin** [comment]
Sorry, forgot all about this PR!  

I was merely waiting for test results before merging.  My original fix didn't work, and therefore I didn't have confidence that my updated fix was good.

Of course I could have tested the fix myself, but that's, like, work...

(The &wrapscan thing is also fixed in that PR.)
