### ISSUE TITLE
"Invalid sign text" issue when launching gvim.

### ISSUE THREAD

**Issue by RFYoung** [mgedmin/coverage-highlight.vim#31]
gvim version: 8.2.4464
python version: 3.10.2
os : manjaro 21.2.4

When staring vim, this would be shown:
```
Error detected while processing /usr/share/vim/vimfiles/plugin/coverage-highlight.vim:
line   16:
E239: Invalid sign text: �~F�
line   23:
E239: Invalid sign text: �~F�
line   30:
E239: Invalid sign text: �~G�
```

**Comment by mgedmin** [comment]
Ooh, interesting!  I've never seen this before but it smells like a charset problem.

Can you please tell me what this prints in Vim:

    :verbose set encoding?

and also

    :!locale charmap

As a workaround, for now you can put this in your ~/.vimrc to avoid non-ASCII characters in signs:

    let g:coverage_sign = '>>'
    let g:coverage_sign_branch = '~>'
    let g:coverage_sign_branch_target = '>~'

(I probably should do that automatically when &encoding is not utf-8)

**Comment by RFYoung** [comment]
for `:verbose set encoding`, the output was:
```
encoding=latin1
```

for `:!locale charmap`, the output was:
```
locale: Cannot set LC_ALL to default locale: No such file or directory
UTF-8

Press ENTER or type command to continue
```

The warning was not shown after I implemented the workaround, thanks!

**Comment by mgedmin** [comment]
> locale: Cannot set LC_ALL to default locale: No such file or directory

You will want to fix this, or you'll have problems all over the place.  I'm not familiar with Manjaro, so I cannot give specific advice, but surely Manjaro support forums exist?

Vim defaulting to Latin-1 is probably a consequence of the above.

I'll make the plugin default to ASCII-only signs in non-UTF-8 locales.

**Comment by RFYoung** [comment]
I changed my locale settings. I set all my locale settings to those in `locale.gen`, and I delete the repetitive and redundant `en_US.UTF8` in the last line in `locale.gen` (there is another one in the middle of file). Then everything seems fine with the default settings (without workaround above).

I guess there exists some bug or design flaw in KDE, manjaro or vim. 

Thanks for your help. :blush:

**Comment by mgedmin** [comment]
The bug is either in Manjaro (if it was that broken out of the box), or in the configuration changes you made to locale-related files.
