### ISSUE TITLE
Document how to change colors

### ISSUE THREAD

**Issue by merwok** [mgedmin/coverage-highlight.vim#4]
Hello!  I am not an expert with color configuration in vim, and the default values of this plugin don’t work for me:

![screen png](https://user-images.githubusercontent.com/635179/32585338-05d1d548-c4cb-11e7-9bc2-fa2faeca1d68.png)

(There is code in a white font after the return keyword, and a `+` sign from git-gutter in the first column.)

Would you mind adding an example config in the README?  I never quite know what to use with ctermbg, guibg, highlight groups and all that.

**Comment by mgedmin** [comment]
Ouch.  Yes, this needs to be improved.

To answer your question quickly, put

    hi NoCoverage ctermbg=darkblue guibg=#ffcccc

in your `~/.vimrc`.  Replace `darkblue` with whatever color you want.  See [`:help cterm-color`](http://vimhelp.appspot.com/syntax.txt.html#cterm-colors) for the names and numbers of the colors you can use.

**Comment by mgedmin** [comment]
I've updated the default highlighting color to work better with a dark terminal background.

I tried all possible 8 colors in a gnome-terminal with the Tango palette, and dark red seems to have the best contrast:

![ekrano nuotrauka is 2017-11-09 13-12-33](https://user-images.githubusercontent.com/159967/32602691-bfbf5a14-c54f-11e7-9724-ab06d493c001.png)

A 256-color terminal is, of course, nicer:

![ekrano nuotrauka is 2017-11-09 13-13-03](https://user-images.githubusercontent.com/159967/32602718-d3782d74-c54f-11e7-99dd-02dce77f8f5d.png)

**Comment by merwok** [comment]
Ah, I remember that I added a setting to force `t_Co=8` some months ago when xfce4-terminal changed its term variable to xterm-256colors and that made my color scheme ugly.  I pull your update and got the flashy red, so I’ll have to experiment to find a better value!

![tmp](https://user-images.githubusercontent.com/635179/32621574-3b662078-c54e-11e7-83f2-d50626f11cf6.png)

Any chance we could get a setting to choose either signs or highlight?  I’d like to keep the git-gutter markers even if I show coverage.

**Comment by mgedmin** [comment]
Can you open a new issue asking for the options?
