### ISSUE TITLE
Need to say `py3 import vim` for this to work.

### ISSUE THREAD

**Issue by jfemiani** [mgedmin/coverage-highlight.vim#6]
Thanks for this tool. 
I am using spacevim (neovim) and I just installed the plugin however when I type:
`:HighlightCoverage`
vim complains about not being able to import vim (from the python module). 

I found that if I type 
`:py3 import vim`
the `:HighlightCoverage` works after that.

I do not know enough about vim to give more details but it seems like something is off wrt python3 support or neovim support?

**Comment by mgedmin** [comment]
It's a bug in `autoload/coverage_highlight.vim`!  Thank you for reporting it.

Try git master, I just pushed a fix.
