### ISSUE TITLE
Support for pytest smother "who tests what" information

### ISSUE THREAD

**Issue by jwhisnant** [mgedmin/coverage-highlight.vim#8]
First of all, thanks for very useful plugin.  This is a feature request to show "who tests what" information as well.

There is a pytest coverage plugin named [smother](https://github.com/chrisbeaumont/smother) which creates a .smother json file. This file lists "who tests what". It is a json file, and very similar in the format of the existing .coverage file. There is also a smother csv output format, if that would be better.

I find myself wanting to be able to do a command on a line in the buffer where I have my code that is just above what is not covered, and then jump to an open buffer with my test file (or open the test file in a new buffer) and then jump to that line number so I can write more tests.

Since it is possible that a single line of code may be tested by multiple test functions, the "first one" is a reasonable choice. Or there may be a way a good way to goto the "best" choice, or "have the user choose".

Other niceties like a list of which functions if multiples in either the quickfix or location window is possible, etc.

**Comment by mgedmin** [comment]
That sounds awesome, but it's probably best to implement this in a separate plugin.

(FWIW I'm not parsing .coverage files, I'm parsing the output of `coverage report -m`, which gives me ranges of line nunbers.)

**Comment by jwhisnant** [comment]
Agree that a separate plugin is probably best. There is an alpha of coverage that has this feature in coverage that was recently released. I hadn't seen that until after I opened the issue.  That is a better choice to get at the data as compared to "smother". Link below has more details.

https://nedbatchelder.com/blog/201810/who_tests_what_is_here.html
